bits: 8
example_gen: "gen"
target: 50
iterations: 100
frequencies: [0.5, 5, 0.5]
amplitudes: [0.1, 4, 0.4]
coeff_r: [0.1,1.1,0.1]
max_attempts: [1,6,1]
difficulties: [10,11,3]
target_bounce: 2
model_list: "model_list.yaml"
palm_key: ""
